# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BrewChanges < Formula
  desc "Interactive changelog viewer for outdated Homebrew packages"
  homepage "https://github.com/garthdw/homebrew-changes"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/garthdw/homebrew-changes/releases/download/v0.2.0/homebrew-changes_0.2.0_darwin_amd64.tar.gz"
    sha256 "e7a3f0bc9970279b1016bb9f50579961fe818178ae5148e79c62846bde1fb67e"

    define_method(:install) do
      bin.install "brew-changes"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/garthdw/homebrew-changes/releases/download/v0.2.0/homebrew-changes_0.2.0_darwin_arm64.tar.gz"
    sha256 "da4730b8d5bd1c8218642f1091a211e1e6f4aa0070265e34b244edc07f3624ee"

    define_method(:install) do
      bin.install "brew-changes"
    end
  end

  test do
    assert_match "Checking for outdated packages", shell_output("#{bin}/brew-changes 2>&1", 0..1)
  end
end
